# PYTHON VERSION : 3.8.0
# PLATFORM : Windows 11 Pro 22H2
#
# This is the main executable file for the Live Weather project, 
# Do not edit this file unless you know what you are doing.

"""
frontend/main.py
─────────────────
Entry point for the PyQt5 desktop frontend.
 
    cd frontend/
    python main.py
 
The frontend does NOT start or bundle the Flask backend.
Set API_BASE_URL in frontend/.env to point at wherever the backend runs.
 
sys.path contract
-----------------
Adds TWO directories before any application import:
  1. <project_root>/frontend/  → "from config…", "from services…", "from ui…"
  2. <project_root>/           → "from shared.constants import …"
No other file in frontend/ touches sys.path.
"""
 
import sys
from pathlib import Path
 
_FRONTEND_DIR = Path(__file__).resolve().parent         # …/frontend/
_PROJECT_DIR  = _FRONTEND_DIR.parent                    # …/ (project root)
 
sys.path.insert(0, str(_PROJECT_DIR))
sys.path.insert(0, str(_FRONTEND_DIR))
 
# ── All application imports below this line ───────────────────────────────────
from PyQt5.QtWidgets import QApplication, QMainWindow
from PyQt5.QtCore import Qt

from ui.mainUI import Ui_MainWindow

from shared.constants import APP_NAME, APP_VERSION 
from services.logger import get_logger
 
log = get_logger(__name__)

class MainWindow(QMainWindow):
    def __init__(self):
        QMainWindow.__init__(self)

        from ui_controller.ui_functions import UIFunctions

        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        
        self.ui_functions = UIFunctions(self)
        self.ui_functions.uiDefinitions()

        # MOVE WINDOW
        def moveWindow(event):
            # Drag window
            if event.buttons() == Qt.LeftButton:
                self.move(
                    self.pos() +
                    event.globalPos() -
                    self.dragPos
                )

                self.dragPos = event.globalPos()
                event.accept()

        self.ui.top_bar_label.mouseMoveEvent = moveWindow
        self.ui.top_bar_label.mouseDoubleClickEvent = moveWindow
        
        self.ui.button_toggle.clicked.connect(lambda: self.ui_functions.toggle(275, True))
        self.ui.button_home.clicked.connect(lambda: self.ui_functions.setHomePage())
        self.ui.button_dashboard.clicked.connect(lambda: self.ui_functions.setDashboardPage())
        self.ui.button_cleaning.clicked.connect(lambda: self.ui_functions.setCleaningPage())
        self.ui.button_report.clicked.connect(lambda: self.ui_functions.setReportPage())
        self.ui.button_about.clicked.connect(lambda: self.ui_functions.setAboutPage())
        self.ui.button_settings.clicked.connect(lambda: self.ui_functions.setSettingsPage())

    # IMPORTANT: this must be outside __init__
    def mousePressEvent(self, event):
        self.dragPos = event.globalPos()
        
        
def main() -> int:
    log.info("Starting %s v%s (frontend)", APP_NAME, APP_VERSION)
 
    QApplication.setAttribute(Qt.AA_EnableHighDpiScaling, True)
    QApplication.setAttribute(Qt.AA_UseHighDpiPixmaps, True)
 
    app = QApplication(sys.argv)
    app.setApplicationName(APP_NAME)
    app.setApplicationVersion(APP_VERSION)
 
    window = MainWindow()
    window.show()
 
    code = app.exec_()
    log.info("Frontend exited with code %d", code)
    return code


# ==>> Calling the main class
if __name__ == '__main__' :
    main()


