# PYTHON VERSION : 3.8.0
# PLATFORM : Windows 11 Pro 22H2
#
# This is the main executable file for the Live Weather project, 
# Do not edit this file unless you know what you are doing.



# importing necessary packages and modules ------------------------------
from PyQt5 import QtWidgets, QtCore, QtGui
from PyQt5.QtCore import Qt, QRect, QPropertyAnimation
from PyQt5.QtWidgets import *
import sys, threading
from ui.mainUI import Ui_MainWindow
# -------------------------------------------------------------------------


class MainWindow(QMainWindow):
    def __init__(self):
        QMainWindow.__init__(self)

        from ui_controller.ui_functions import UIFunctions

        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        
        self.ui_functions = UIFunctions(self)
        self.ui_functions.uiDefinitions()

        # MOVE WINDOW
        def moveWindow(event):
            # Drag window
            if event.buttons() == Qt.LeftButton:
                self.move(
                    self.pos() +
                    event.globalPos() -
                    self.dragPos
                )

                self.dragPos = event.globalPos()
                event.accept()

        self.ui.top_bar_label.mouseMoveEvent = moveWindow
        self.ui.top_bar_label.mouseDoubleClickEvent = moveWindow
        
        self.ui.button_toggle.clicked.connect(lambda: self.ui_functions.toggle(275, True))
        self.ui.button_home.clicked.connect(lambda: self.ui_functions.setHomePage())
        self.ui.button_dashboard.clicked.connect(lambda: self.ui_functions.setDashboardPage())
        self.ui.button_cleaning.clicked.connect(lambda: self.ui_functions.setCleaningPage())
        self.ui.button_report.clicked.connect(lambda: self.ui_functions.setReportPage())
        self.ui.button_about.clicked.connect(lambda: self.ui_functions.setAboutPage())
        self.ui.button_settings.clicked.connect(lambda: self.ui_functions.setSettingsPage())

    # IMPORTANT: this must be outside __init__
    def mousePressEvent(self, event):
        self.dragPos = event.globalPos()


# ==>> Calling the main class
if __name__ == '__main__' :
    app = QApplication(sys.argv)
    win = MainWindow()
    win.show()
    sys.exit(app.exec_())


